### ISSUE TITLE
New Release for sexy pre-commit hooks rev

### ISSUE THREAD

**Issue by chmuche** [quwac/pyproject-autoflake#3]
My issue is to ask for a new release like `1.0.2` following the work of @cfd1 

In a sample project, add a `.pre-commit-config.yml` file.
We need to add a direct ref to the latest commit sha1 `d09a6b9a9b9f0630c4e349e094d7b2cacb86e3ac`
It will be much prettier if `rev: 1.0.2` is used instead of `rev: d09a6b9a9b9f0630c4e349e094d7b2cacb86e3ac`

This doesn't work
```yml
repos:
  - repo: https://github.com/quwac/pyproject-autoflake
    rev: 1.0.1
    hooks:
      - id: pautoflake
```
but this yes
```yml
repos:
  - repo: https://github.com/quwac/pyproject-autoflake
    rev: d09a6b9a9b9f0630c4e349e094d7b2cacb86e3ac
    hooks:
      - id: pautoflake
```

Thanks for your awesome work by the way :+1:
